### ISSUE TITLE
Google Organic Traffic Showing as Direct Medium

### ISSUE THREAD

**Issue by davidsculbertson** [plausible/docs#373]
Hello,

I have been running Plausible side-by-side with GA3 for a couple of days now. Yesterday was the day of complete data. Both platforms were pretty close in the total sessions count, but Plausible's distribution among the mediums/channels is wildly different from GA3. Here's direct versus organic breakdown (direct/organic) for all both for the same 24 hours:

GA3: 8/48
Plausible: 45/16

In taking a look at the Organic sources in Plausible, there are ZERO sessions from Google which is basically impossible. 

Why would be Plausible categorizing Google Organic visits as Direct??

**Comment by metmarkosaric** [comment]
thanks for reaching out @davidsculbertson! 

could you please contact us with more details as it's difficult to troubleshoot what's going on without at least your domain name? our customer support can be reached via https://plausible.io/contact. thanks! 

i'll close this now as we keep this repo for improvements to our documentation only rather than for support questions. thank you!
